export const staticWeather = {
  location: "Гомель",
  time: "2024-06-01 17:57",
  currentTemperature: 26,
  dayTemperature: 26.8,
  nightTemperature: 13.5,
  conditionText: "Light rain shower",
  conditionIcon: "//cdn.weatherapi.com/weather/64x64/day/353.png",
  windMPH: 6.9,
  humidity: 51,
  chanceOfRain: 95,
  dateOne: "02.06.2024",
  dayTemperatureOne: 25.9,
  nightTemperatureOne: 16,
  dayConditionTextOne: "Sunny",
  dayConditionIconOne: "//cdn.weatherapi.com/weather/64x64/day/113.png",
  nightConditionTextOne: "Clear ",
  nightConditionIconOne: "//cdn.weatherapi.com/weather/64x64/night/113.png",
  dateTwo: "03.06.2024",
  dayTemperatureTwo: 22.4,
  nightTemperatureTwo: 13.7,
  dayConditionTextTwo: "Light rain shower",
  dayConditionIconTwo: "//cdn.weatherapi.com/weather/64x64/day/353.png",
  nightConditionTextTwo: "Clear ",
  nightConditionIconTwo: "//cdn.weatherapi.com/weather/64x64/night/113.png",
}
